//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc triangle.hlsl -Od -Zi -T ps_5_0 -E mainPS -Fo triangle_ps.cso -Fc
//    triangle_ps.asm
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v1.xyzw
dcl_output o0.xyzw

#line 24 "C:\Users\Leovan\Desktop\render_engine\resources\shaders\triangle.hlsl"
mov o0.xyzw, v1.xyzw  // mainPS<0,1,2,3>
ret 
// Approximately 2 instruction slots used
