//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc triangle.hlsl -Od -Zi -T vs_5_0 -E mainVS -Fo triangle_vs.cso -Fc
//    triangle_vs.asm
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// COLOR                    0   xyz         1     NONE  float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 2

#line 16 "C:\Users\Leovan\Desktop\render_engine\resources\shaders\triangle.hlsl"
mov r0.xyz, v0.xyzx  // output<0,1,2>
mov r0.w, l(1.000000)  // output<3: 1f>
mov r1.xyz, v1.xyzx  // output<4,5,6>
mov r1.w, l(1.000000)  // output<7: 1f>
mov o0.xyzw, r0.xyzw  // mainVS<0,1,2,3: 1f>
mov o1.xyzw, r1.xyzw  // mainVS<4,5,6,7: 1f>
ret 
// Approximately 7 instruction slots used
